[project]
name = "eixn-pos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black>=26.1.0",
    "pillow>=12.1.1",
    "pyside6>=6.10.1",
]
